version: '3.7'

services:
    clutrack:
        build: .
        volumes:
            - ./app:/usr/src/app
        ports:
            - 8000:4410
        environment:
            - PYTHONBUFFERED=1
        command: gunicorn -w 4 app:app --bind=0.0.0.0:4410