version: '3.7'

services:
    clutrack:
        build: .
        volumes:
            - .:/usr/src
        ports:
            - 8000:5000
        environment:
            - PYTHONBUFFERED=1
            - ENV=local
            - FLASK_DEBUG=1
        command: flask run