version: '3.7'

services:
    clutrack:
        build: .
        volumes:
            - .:/usr/src
        ports:
            - 5000:5000
        environment:
            - PYTHONBUFFERED=1
            - ENV=local
            - FLASK_DEBUG=1
        command: gunicorn -w 4 app:app --bind=0.0.0.0:5000